#추후 시크릿매니저 사용
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e954f86bedb0cd880a2d01e100cb32d6
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789